# openapi2-functions-v3.yaml
swagger: '2.0'
info:
  title: api-poc-edf-v3
  description: API on API Gateway with a Google Cloud Functions
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /prompt:
    get:
      summary: ask gemini
      operationId: prompt
      x-google-backend:
        address: https://europe-west1-poc-chatbot-edf.cloudfunctions.net/simple-gemini-function
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /prompt-body:
    post:
      summary: ask gemini with prompt in the body
      operationId: prompt-body
      x-google-backend:
        address: https://europe-west1-poc-chatbot-edf.cloudfunctions.net/simple-gemini-function
      consumes:
        - application/json
      parameters:
        - in: body
          name: prompt
          description: prompt to use
          schema:
            type: object
            required:
              - prompt
            properties:
               prompt:
                 type: string
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /photo:
    post:
      summary: ask gemini with prompt and a photo uri
      operationId: photo
      x-google-backend:
        address: https://europe-west1-poc-chatbot-edf.cloudfunctions.net/photo-gemini-function
      consumes:
        - application/json
      parameters:
        - in: body
          name: prompt
          description: prompt and picture to use
          schema:
            type: object
            required:
              - prompt
              - image_type
              - image_uri
            properties:
               prompt:
                 type: string
               image_type:
                 type: string
               image_uri:
                 type: string
      responses:
        '200':
          description: A successful response
          schema:
            type: string